# 默认启动环境

spring.profiles.active=dev
spring.application.name=case-server


server.port=8443





spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.maxActive=20
spring.datasource.druid.maxWait=60000
spring.datasource.druid.timeBetweenEvictionRunsMillis=60000
spring.datasource.druid.minEvictableIdleTimeMillis=300000
spring.datasource.druid.validationQuery=SELECT 1
spring.datasource.druid.testWhileIdle=true
spring.datasource.druid.testOnBorrow=false
spring.datasource.druid.testOnReturn=false
spring.datasource.druid.poolPreparedStatements=true
spring.datasource.druid.keepAlive=true
spring.datasource.druid.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.druid.connectionProperties=druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

# Redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.timeout=300ms
spring.redis.lettuce.pool.max-active=100
spring.redis.lettuce.pool.max-idle=50
spring.redis.lettuce.pool.max-wait=500ms


https.ssl.enable=true
https.ssl.key-store=classpath:keystore.p12
https.ssl.key-store-password=12345678
https.ssl.keyStoreType=PKCS12
https.ssl.keyAlias=tomcat

http.port=8094

#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl




mybatis.typeAliasesPackage=com.xiaoju.framework.*
mybatis.mapperLocations=classpath*:mapper/*.xml

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=101MB

#spring.datasource.druid.connection-init-sqls=set names utf8mb4

# log
logging.config=classpath:log4j2.xml


web.upload-path=${user.home}/casemind_uploads/
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.encoding=utf-8
spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false
spring.mvc.static-path-pattern=/**
spring.resources.static-locations=classpath:/web/dist/,file:${web.upload-path}
spring.thymeleaf.prefix=classpath:/web/dist/
spring.thymeleaf.suffix=.html


spring.devtools.add-properties=false


authority.flag=false

session.previous-version-history-size=5
